### ISSUE TITLE
Heart Colors Not Working in Firefox at Top of Posts

### ISSUE THREAD

**Issue by chriscoyier** [CodePen/redesign#194] opened 2015-10-03 20:21 UTC
<img width="1209" alt="screen shot 2015-10-03 at 3 20 45 pm" src="https://cloud.githubusercontent.com/assets/69156/10264947/5df959ee-69e2-11e5-85cf-63fa840a96a0.png">

**Comment by tholman** [comment] 2015-10-04 04:23
Dupe of #182

**Closed by tholman** 2015-10-04 04:23 UTC
