### ISSUE TITLE
HTML editor content vanishes when comment modal is open

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/redesign#225] opened 2015-10-06 23:56 UTC
So... this seems to happen in a few circumstances. Here's the only one I can reproduce 100% of the time:

1) Default view
![screen shot 2015-10-06 at 4 53 29 pm](https://cloud.githubusercontent.com/assets/8040471/10325985/1b523ec4-6c4b-11e5-9b0b-a4341d229f77.png)

2) Click comments

![screen shot 2015-10-06 at 4 53 42 pm](https://cloud.githubusercontent.com/assets/8040471/10325988/20ec9186-6c4b-11e5-872c-551ee99f7909.png)

3) Click into HTML editor, text vanishes 
![screen shot 2015-10-06 at 4 53 47 pm](https://cloud.githubusercontent.com/assets/8040471/10325990/275be0e4-6c4b-11e5-9c71-c260b0652d80.png)

**Comment by chriscoyier** [comment] 2015-10-07 00:25
Confirmed. SO WEIRD. Can't replicate in dev but can on prod. 

JS error throws:

```
Uncaught TypeError: CodeMirror.countColumn is not a function
```

Any ideas @desandro or @quezo ?

**Comment by desandro** [comment] 2015-10-09 15:38
Looks like issue was loading a quickie version of `CodeMirror` typically used in comments, which was overwriting the previous `CodeMirror`. Assigning to quezo :large_orange_diamond:

**Comment by chriscoyier** [comment] 2015-10-09 17:24
Fixed this.

**Closed by chriscoyier** 2015-10-09 17:24 UTC
