### ISSUE TITLE
Preview resizing doesn't work as expected

### ISSUE THREAD

**Issue by mariemosley** [CodePen/redesign#230] opened 2015-10-07 13:51 UTC
Members are having difficulty testing responsive designs because the preview pane only resizes as expected in one direction. Screencast demonstrating the issue: http://d.pr/v/10VVn/4vFJhWWN

**Comment by bekahsealey** [comment] 2015-10-07 17:12
I ran into this problem today, trying to test a flexbox layout. Wasn't sure if it was just me. This is the pen I was creating: http://codepen.io/bekahsealey/pen/ojWRve.

**Comment by TropicalHenry** [comment] 2015-10-07 18:24
Hey, im having the same issue. I have tried 3 different browsers on two different computers. The issue is effecting all pens that i view or create and its been this way since yesterday morning.

**Comment by TropicalHenry** [comment] 2015-10-07 18:39
Also im getting problems resizing the preview pane from both sides. The pen content just gets stuck at 1000px even when the browser is smaller.
If i go to Change View > Details View then the pens do become responsive again.
Maybe that helps.....

**Comment by chriscoyier** [comment] 2015-10-07 20:12
Got a fix for this going out now, sorry gang.

**Closed by chriscoyier** 2015-10-07 20:12 UTC
