### ISSUE TITLE
Can't close the pen settings modal

### ISSUE THREAD

**Issue by shadeed** [CodePen/redesign#97] opened 2015-10-01 14:33 UTC
In case I added more than 2 external resources, the modal won't close.. Even if the default state, with 2 empty fields, the close button is cutted off.

Default (2 fields):
<img width="770" alt="screen shot 2015-10-01 at 5 31 10 pm" src="https://cloud.githubusercontent.com/assets/8038659/10223510/f2bcdf42-6861-11e5-9b60-aaf101af5505.png">

4 fields
<img width="752" alt="screen shot 2015-10-01 at 5 30 51 pm" src="https://cloud.githubusercontent.com/assets/8038659/10223511/f2c33e0a-6861-11e5-9665-c1d38838d6a3.png">

Seen on my Macbook Pro, 15.4".

**Comment by Fotiman** [comment] 2015-10-01 15:24
This appears to be a duplicate of issue #92

**Closed** 2015-10-01 15:32 UTC
