### ISSUE TITLE
Template Dropdown can be Empty

### ISSUE THREAD

**Issue by donebydavid** [CodePen/redesign#84] opened 2015-10-01 13:51 UTC
When attempting to use the new pen from template menu it doesn't display on the settings pages

![image](https://cloud.githubusercontent.com/assets/14917878/10222434/455887f8-6897-11e5-9550-87f9fbbb60a8.png)

**Comment by chriscoyier** [comment] 2015-10-01 15:36
We've had a few reports of this but I'm having some trouble figuring it out. Tried PRO and Non-PRO accounts. Logged out you don't get the arrow dropdown at all.

It does make an XHR request for the templates when you open it for the first time, I wonder if that can fail somehow. Do you see any errors in the console?

**Comment by pixelass** [comment] 2015-10-01 16:57
I had the same issue before I created a template. PRO account. I did not look into the console ;(

**Comment by donebydavid** [comment] 2015-10-01 21:43
@chriscoyier @quezo - I'm getting this in my console

>Mixed Content: The page at 'https://codepen.io/donebydavid/settings/account' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://codepen.io/templates'. This request has been blocked; the content must be served over HTTPS.

**Comment by chriscoyier** [comment] 2015-10-01 21:49
@donebydavid I bet that's exactly what the problem is. Does it not work on settings pages, but does work on pages like the homepage?

**Comment by donebydavid** [comment] 2015-10-01 22:46
@chriscoyier correct, settings is the only place I can replicate the issue (only area forcing https that I can see)

**Comment by quezo** [comment] 2015-10-05 15:41
Sweet find. This is fixed now.

**Closed by quezo** 2015-10-05 15:41 UTC
