### ISSUE TITLE
Keybindings button displays as missing character in Chrome on Windows

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/redesign#196] opened 2015-10-03 22:58 UTC
![capture](https://cloud.githubusercontent.com/assets/8040471/10265486/4e0bb54a-69e7-11e5-8d6e-e068cf85f9ea.PNG)

Seems to be okay on Firefox.

**Comment by tholman** [comment] 2015-10-04 03:56
Duplicate of #81, chrome definitely seems to be the culprit though! :)

**Closed by tholman** 2015-10-04 03:56 UTC
