### ISSUE TITLE
chat in professor mode

### ISSUE THREAD

**Issue by oliverholretz** [CodePen/redesign#203] opened 2015-10-04 20:15 UTC
Even though this might not be a bug: 
The button to open and close the chat in professor mode looks like the old button and it's still bigger than the footer of the editor.
![screenshot-codepen io 2015-10-04 22-15-03](https://cloud.githubusercontent.com/assets/10248190/10270005/7340d3e6-6ae5-11e5-8769-1c92b93d2b10.png)

**Comment by chriscoyier** [comment] 2015-10-07 20:35
I kinda like that it's bigger so it looks more tab-like and openable. I'm not in love with the design, so we'll figure out something better at some point. Closing now though because not a bug.

**Closed by chriscoyier** 2015-10-07 20:35 UTC
