### ISSUE TITLE
settings vertical size

### ISSUE THREAD

**Issue by findoff** [CodePen/redesign#101] opened 2015-10-01 15:02 UTC
Pen css settings too big, and close button outside screen.

In profile screen, first who i see instead my pens, its big my nickname with default avatar, and LOT useless space.

chrome, 1366x768 laptop.

Yes, resolution too small, but i loved this site. \*SAD\*

**Comment by Fotiman** [comment] 2015-10-01 15:25
Duplicate of issue #92

**Comment by chriscoyier** [comment] 2015-10-01 16:08
Fixin in next push

**Closed by chriscoyier** 2015-10-01 16:08 UTC
