### ISSUE TITLE
Clicking the thumbnail to open my pen almost deleted the pen!

### ISSUE THREAD

**Issue by bekahsealey** [CodePen/redesign#233] opened 2015-10-07 17:17 UTC
While not exactly a bug, it was startling to realize how easily I could have deleted my pin if I wasn't fully processing the alert. When quickly clicking on a thumbnail, the delete pops up at the exact same time as the click, leaving this open to potentially occurring on a badly placed click.

**Comment by chriscoyier** [comment] 2015-10-07 17:25
Thanks for the feedback! We'll have to digest this some. It's the first feedback of this kind we've heard (but I understand exactly what you mean). I'm going to close this issue though, as it's not a bug.

**Closed by chriscoyier** 2015-10-07 17:25 UTC
