### ISSUE TITLE
Lines around the user image on profile page

### ISSUE THREAD

**Issue by tobireif** [CodePen/redesign#241] opened 2015-10-08 14:01 UTC
On http://codepen.io/TobiReif/ there's a dark border around the user image, in Chrome and in FF.

But in Chrome the border itself has "borders" / three lighter lines.

**Comment by chriscoyier** [comment] 2015-10-08 14:19
Bug caused by using transform to center. @tholman has a fix idea.

![slack-imgs com](https://cloud.githubusercontent.com/assets/69156/10369019/b3621268-6d9d-11e5-865f-22b0a99e811b.png)

**Comment by tholman** [comment] 2015-10-08 22:08
Will be fixed at the next deploy :)

**Closed by tholman** 2015-10-08 22:08 UTC
